### ISSUE TITLE
Number of GPUs

### ISSUE THREAD

**Issue by JosephKJ** [hongjoon0805/SS-IL-Official#1]
Hi @hongjoon0805 , 

Thanks for your amazing work and the neat code-base. Thanks for sharing it. 

How many GPUs did you use for your experiments? Approximately how much time does an experiment take?

Thanks,
Joseph

**Comment by hongjoon0805** [comment]
Hi Joseph,

Thank you for giving interest to our project.

For the experiment, we used two kinds of GPUs, 1080 TI and TiTAN RTX 6000, and we usually used 4 GPUs.

For the running time, It takes about 30 hours if we used 1080 Ti.

Thanks,
Hongjoon

**Comment by JosephKJ** [comment]
Thank you very much for your quick response, Hongjoon! Much appreciated!
