### ISSUE TITLE
command parameters: base-classes and -step-size?

### ISSUE THREAD

**Issue by qsunyuan** [hongjoon0805/SS-IL-Official#4]
Amazing work and coding.

I just started to study the Continual Learning soon.

I want to ask if my understanding is correct.

For example, ImageNet-1K.

According to code:

`tasknum = (dataset.classes-args.base_classes)//args.step_size+1  `

base-classes: 500, -step-size:5
Does it mean: I first directly train a 500 class classifier, and then it has 5 tasks next, namely (600, 700, 800, 900, 1000)

Hope to get ur replay early.

Thx.

**Comment by qsunyuan** [comment]
update: 
base-classes: 500, -step-size:100
Does it mean: I first directly train a 500 class classifier, and then it has 5 tasks next, namely (600, 700, 800, 900, 1000)

**Comment by hongjoon0805** [comment]
Hi, thank you for giving interest to our project

I think you correctly understand our code implementation.

if base-classes:500, step-size:100, we first train a 500 classes classifier, and then we train 5 consecutive tasks, namely (500~599, 600~699, 700~799, 800~899, 900~999)

Best,
Hongjoon
