### ISSUE TITLE
I got poor CIFAR100 results.

### ISSUE THREAD

**Issue by qsunyuan** [hongjoon0805/SS-IL-Official#5]
Nice work.

As ImageNet1K or Landmark is too large.

I first trained your method on a relatively small data set (CIFAR100).

Howerver, I got a poor results.

I trained a base 50 classifier, then, follows a 5 task with 10 new classes per step.

according to https://github.com/hongjoon0805/SS-IL-Official/issues/3#issuecomment-968392071

nepochs: 200
schedule: 80 120 160
gammas: 0.1 0.1 0.1
memory budget: 2000
weigfht decay: 0.001

The final test-top-1 acc is about 51.16%.

**Comment by qsunyuan** [comment]
Could u pls share some results of CIFAR100 or parameter settings insight.
thanks. best wishes.

**Comment by hongjoon0805** [comment]
Hi, sorry for the late reply.

When we trained SS-IL on CIFAR-100, we also got very poor results. I guess SS-IL only works on large scale dataset such as ImageNet or Landmark dataset. 

In my opinion, the reason for the poor result on small scale dataset is that a model trained with small scale dataset has little bias than with large scale dataset. SS-IL only focuses on removing the score bias between old (minor) and new (major) classes.

**Comment by qsunyuan** [comment]
Thank you very much for your patience and quick reply, it really helped me a lot.
Have a good day.

**Comment by JosephKJ** [comment]
Maybe you should try setting `--factor 1` too, so that each incremental step gets 200 epochs...

**Comment by HenryZ94264** [comment]
I'm now training with CIFAR-100 too, maybe you can follow the settings in the paper **iCaRL: Incremental Classifier and Representation Learning**
