### ISSUE TITLE
About iCaRL. ExemplarLoader.

### ISSUE THREAD

**Issue by qsunyuan** [hongjoon0805/SS-IL-Official#6]
Could you pls remind me, how does Exemplar's data set feed into the model?

I only found use the Incremental dataloader. And the incremental dataloader is only related to the tr_idx.

Look for your reply. Thx.

https://github.com/hongjoon0805/SS-IL-Official/blob/8c323811f99f6da8e8d794b663c43bfe63864a3f/data_handler/incremental_loader.py#L194

https://github.com/hongjoon0805/SS-IL-Official/blob/8c323811f99f6da8e8d794b663c43bfe63864a3f/trainer/icarl.py#L31

**Comment by hongjoon0805** [comment]
Hi!

line 93~96 in data_handler/incremental_loader.py, we have
if self.args.trainer != 'ssil' and self.args.trainer != 'lwf':
    self.tr_idx = list(self.tr_idx) + self.exemplar

Therefore, we add self.exemplar to self.tr_idx.

Thanks

**Comment by qsunyuan** [comment]
Thank you so much for your help.
